apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: go-demo
  namespace: go-demo
spec:
  interval: 5m
  chart:
    spec:
      chart: go-demo
      version: '0.2.0'
      sourceRef:
        kind: HelmRepository
        name: joostvdg
        namespace: tanzu-helm-resources
      interval: 1m
  values:
    image:
      tag: "2.7.0"
    httpproxy:
      enabled: true
      fqdn: demo1.services.h2o-2-7459.h2o.vmware.com
      prefix: /
      replacement: /